# Inicialización de la física
/run/initialize

# Configuración de la visualización
/control/execute visual_cosmic.mac

/gps/verbose 0

# Configuración de la partícula
/gps/particle mu-
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 1000 0.01
/gps/hist/point 1500 0.015
/gps/hist/point 2000 0.02
/gps/hist/point 2500 0.025
/gps/hist/point 3000 0.03
/gps/hist/point 3500 0.035
/gps/hist/point 4000 0.04
/gps/hist/point 4500 0.045
/gps/hist/point 5000 0.05
/gps/hist/point 5500 0.055
/gps/hist/point 6000 0.06
/gps/hist/point 6500 0.065
/gps/hist/point 7000 0.07
/gps/hist/point 7500 0.075
/gps/hist/point 8000 0.08
/gps/hist/point 8500 0.085
/gps/hist/point 9000 0.09
/gps/hist/point 9500 0.095
/gps/hist/point 10000 0.1
/gps/hist/inter Spline

# Distribución de la fuente
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 -100000 cm
/gps/pos/radius 30.5 cm

# Angulo calculado 
/gps/ang/type planar
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 1 0
/gps/ang/maxtheta 0 deg

/run/beamOn 1000
